# Generated by Django 5.1.5 on 2025-03-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='description',
            new_name='Additional_Details',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='name',
            new_name='Transaction_Name',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='category',
            new_name='Transaction_Type',
        ),
    ]
