# Generated by Django 5.1.5 on 2025-03-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_description_expensemodel_additional_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='Transaction_Type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='Additional_Details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='Transaction_Name',
            new_name='name',
        ),
    ]
